### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Camilovelag** [belmeetmule/Portfolio#8]
Hi Mulugeta!

Good job working on your web page. Keep working! 💪

You need to work on these issues to improve your page and reach a fantastic webpage display.

✅ Use a proportional unit of measure (e.g. em, rem, %) to size images.
✅ Use `main` tag instead of the generic `div` tag for better SEO.

Cheers! 👍

**Comment by belmeetmule** [comment]
fixed !!
